from .image_upload import NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS
from .image_upload import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS
from .image_compare import NODE_CLASS_MAPPINGS as COMPARE_NODE_CLASS_MAPPINGS
from .image_compare import NODE_DISPLAY_NAME_MAPPINGS as COMPARE_NODE_DISPLAY_NAME_MAPPINGS
from .image_padding import NODE_CLASS_MAPPINGS as PADDING_NODE_CLASS_MAPPINGS
from .image_padding import NODE_DISPLAY_NAME_MAPPINGS as PADDING_NODE_DISPLAY_NAME_MAPPINGS
from .image_crop_stitch import NODE_CLASS_MAPPINGS as CROP_NODE_CLASS_MAPPINGS
from .image_crop_stitch import NODE_DISPLAY_NAME_MAPPINGS as CROP_NODE_DISPLAY_NAME_MAPPINGS
from .operations import NODE_CLASS_MAPPINGS as OPERATION_NODE_CLASS_MAPPINGS
from .operations import NODE_DISPLAY_NAME_MAPPINGS as OPERATION_NODE_DISPLAY_NAME_MAPPINGS
from .ui import NODE_CLASS_MAPPINGS as UI_NODE_CLASS_MAPPINGS
from .ui import NODE_DISPLAY_NAME_MAPPINGS as UI_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **OPERATION_NODE_CLASS_MAPPINGS,
    **IMAGE_NODE_CLASS_MAPPINGS,
    **COMPARE_NODE_CLASS_MAPPINGS,
    **PADDING_NODE_CLASS_MAPPINGS,
    **CROP_NODE_CLASS_MAPPINGS,
    **UI_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **OPERATION_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **COMPARE_NODE_DISPLAY_NAME_MAPPINGS,
    **PADDING_NODE_DISPLAY_NAME_MAPPINGS,
    **CROP_NODE_DISPLAY_NAME_MAPPINGS,
    **UI_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
